### ISSUE TITLE
mt7628.ko failed to nmap

### ISSUE THREAD

**Issue by drcyberg** [Nossiac/mtk-openwrt-feeds#108]
Hi All!

I use this repository for my mt7628 (skw92a) chip module in Openwrt Snapshot version, and write this message both boot:

`kmodloader: failed to mmap /lib/modules/4.14.121/mt7628.ko`

The file size is 0 byte. What is the solution?

Thank you!

Regards!

**Comment by Khomyak-sibiryak** [comment]
Try editing the Makefile as indicated in the next post https://github.com/Nossiac/mtk-openwrt-feeds/issues/106#issuecomment-485039812
