### ISSUE TITLE
MediaTek MT7602EN

### ISSUE THREAD

**Issue by build000** [Nossiac/mtk-openwrt-feeds#14]
If possible add MediaTek MT7602EN drivers ? - this requires to https://wikidevi.com/wiki/MQmaker_WiTi_Board (Lede 17.01-SNAPSHOT).

**Comment by Nossiac** [comment]
AFAK, mt7602 actually shares driver with mt7612, before it works, a few configuration options need to be updated first. An init version can be uploaded this week.

**Comment by Nossiac** [comment]
https://github.com/Nossiac/mtk-openwrt-feeds/commit/fe0c9c797f10e75453c4ca468a08f1557ef76ae8   added 7602 support ( it actually shares driver with mt7612).
The ko module will be refreshed in a couple of hours.

**Comment by build000** [comment]
Thx.
I will test how soon it will be possible and possibly I will answer whether and what are the problems under WiTi.
