### ISSUE TITLE
Kernel 4.14

### ISSUE THREAD

**Issue by Lu-Fi** [Nossiac/mtk-openwrt-feeds#25]
Can you please provide Kernel Modules also for 4.14 ?

**Comment by Nossiac** [comment]
I've done the necessary patch to build these drivers for 4.14.
The automation server needs a few hours to build it. Maybe tmr.

**Comment by Nossiac** [comment]
[http://nossiac.com/download/mtk-wifi-ko/](http://nossiac.com/download/mtk-wifi-ko/)

module for 4.14 updated, not verified yet.

**Comment by BGFWDev** [comment]
Any plans for 4.14 for MT7623?

**Comment by Nossiac** [comment]
@BGFWDev 

[http://nossiac.com/download/mtk-wifi-ko/mt7615-for-mt7623-linux-4.14.23.ko](http://nossiac.com/download/mtk-wifi-ko/mt7615-for-mt7623-linux-4.14.23.ko)

NOT verified.

**Comment by BGFWDev** [comment]
is there a MT7623+MT7615 file update? We are having issues getting this one to work. Or an MT7623+MT7612 .ko file?

**Comment by frank-w** [comment]
can you post the patch for making driver for 4.4 can be compiled in 4.14?
