### ISSUE TITLE
Support adhoc?

### ISSUE THREAD

**Issue by slthomason** [Nossiac/mtk-openwrt-feeds#27]
I am using 2 pieces of MT7621-based hardware (ZBT-WE1326 and ZBT-WG3526) that both have mt7612 (5G) and mt7603 (2.4G) chipsets.  They are basically the same with a very few board differences.

I was wondering if these drivers support adhoc mode?  I wasn't able to see how to enable it in the Luci screens, but maybe that is settings we would have to enable manually in the configs (not Luci)?

If so, can you please let me know how we would set it?

**Comment by Nossiac** [comment]
No, it does not support adhoc. There are only 2 modes available: AP mode, APCli Mode.
