### ISSUE TITLE
vfs_write dropped

### ISSUE THREAD

**Issue by brick2008** [Nossiac/mtk-openwrt-feeds#33]
Hi,
     After 4.14.23 compiled and test it, I got a error:
[  257.928632] mt7615: module license 'Proprietary' taints kernel.
[  257.940442] Disabling lock debugging due to kernel taint
[  257.993111] mt7615: Unknown symbol vfs_write (err 0)
[  258.003071] mt7615: Unknown symbol vfs_read (err 0)
google it I found this:
https://github.com/kaloz/mwlwifi/issues/259
I hope it will help you.

**Comment by Nossiac** [comment]
Thanks for your sharing. The issue has been fixed in the local build, will push to the server soon.

**Comment by Nossiac** [comment]
all patch done.
