### ISSUE TITLE
Can't get "mt7628.ko" working in AP Client mode

### ISSUE THREAD

**Issue by docbee63** [Nossiac/mtk-openwrt-feeds#37]
So far I had no success to have the mt7628 operating as AP client. Is the mt7628.ko compiled in a way that supports having it operating as a client to an existing WLAN only? If so, is there an example for a working "mt7628.dat" and "/etc/config/network" and "/etc/config/wireless"?

I tried as how I do with lede on other platforms (where lede is natively supporting WLAN), but no success so far.

**Comment by Nossiac** [comment]
It has nothing to do with "/etc/config/network" and "/etc/config/wireless". The best practice of configuring apcli0 interface is to use "iwpriv" command, and using mt7628.dat as a database only.

Here's an example:

```
iwpriv apcli0 set ApCliEnable=0          // disable client mode first
iwpriv apcli0 set ApCliAuthMode=WPA2PSK  // root ap authentication mode
iwpriv apcli0 set ApCliEncrypType=AES    // root ap encryption type
iwpriv apcli0 set ApCliSsid=HelloHi      // root ap ssid
iwpriv apcli0 set ApCliWPAPSK=12345678   // root ap password
iwpriv apcli0 set ApCliSsid=HelloHi      // root ap ssid, again...
iwpriv apcli0 set ApCliEnable=1          // enable client mode
```

**Comment by docbee63** [comment]
thanks that solved the issue!
