### ISSUE TITLE
Modules for mt7628 with 4.14.x kernel are missing

### ISSUE THREAD

**Issue by DavideFioravanti** [Nossiac/mtk-openwrt-feeds#46]
Modules for mt7628 with 4.14.x kernel are missing.
If it's not possible to compille every module for mt7628, I need just these 2 files:
mt7610-for-mt7628-linux-4.14.32.ko
mt7628-for-mt7628-linux-4.14.32.ko

Thank you.

**Comment by Nossiac** [comment]
It turns out that openwrt trunk has merged mt7628 and mt7688 into a single target "mt76x8", which leads to my automation server failed to publish the modules....

so what your are looking for is actually (kernel already updated to v34):
```
mt7610-for-mt76x8-linux-4.14.34.ko
mt7628-for-mt76x8-linux-4.14.34.ko
```
