### ISSUE TITLE
new kernel version  4.9.67 from lede

### ISSUE THREAD

**Issue by zhaibin18** [Nossiac/mtk-openwrt-feeds#5]
the source from lede build with kernel version 4.9.67

**Comment by Nossiac** [comment]
Sorry, I'm a little busy these days.
Will come back on this project next week, I think.

**Comment by MiltonLai** [comment]
The kernel is 4.9.70 now, guys...

**Comment by Nossiac** [comment]
It was planned to follow the stable release only, that is lede-17.01.
Since the ko is too big for a git rpo, I'm gonna refactor it a little bit. hopefully , can be done this week.

**Comment by recyard** [comment]
Hope there are 4.9 kernel modules someday, since my router model (Netgear R6220) only has support in LEDE master(development) branch with 4.9 kernel.

**Comment by zhaibin18** [comment]
I used a Phicomm K2P router only works with LEDE master branch with 4.9 kernel，Hope there is 4.9 kernel support, Many thanks!

**Comment by chd1998** [comment]
Waiting for the new support of 4.9.*, Thanx a lot for your effort!

**Comment by chd1998** [comment]
Can anybody help me with these errors?  Thanx in advance...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-autoreboot:
 * 	libuci-lua (>= 2018-01-01) * 
 * opkg_install_cmd: Cannot install package luci-app-autoreboot.
package/Makefile:64: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/chendong/lede/lede'
package/Makefile:106: recipe for target '/home/chendong/lede/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install' failed
make[1]: *** [/home/chendong/lede/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/chendong/lede/lede'
/home/chendong/lede/lede/include/toplevel.mk:207: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by Nossiac** [comment]
some of the drivers were developed with linux 2.6, they are too old to build with kernel 4.9, a lot of code needs to be rewritten. also it seems lede-master adopted a more strict compiling policy, which produced more errors than lede-17.01. that is to say, it will take longer than I expected, hope that won't fail this project, 😆 😆

**Comment by MaFeSa** [comment]
> hope that won't fail this project
😱
We hope not 🙏

**Comment by Vonger** [comment]
Hi, I find your github on google, it save me a lot of time do the script👍 
I success compile it for Linux 4.9, just a lot of tricky. 
please update your ko to this mt7628.ko: 
md5: 31fd66c1606abc14c0fdf6eb941f4807
Feel free to email me if any question :)

**Comment by Nossiac** [comment]
@Vonger thanks for your work! what's the exact kernel version?
I didn't get my hands on 4.9 support for the last 2 weeks. is it possible to send me those patches you made for 4.9? That way the automation server will build and post the ko with the latest kernel everyday.

**Comment by Vonger** [comment]
It will work for all Linux 4.9 version, actually it is not necessary to make for every linux subversion unless its interface changed. Currently my patches have to manually run, something wrong with the Makefile, please send me your patch for 4.4 so I can combine them and send back to you.

On 17 Jan 2018, at 07:52, Hua Shao <notifications@github.com<mailto:notifications@github.com>> wrote:


@Vonger<https://github.com/vonger> thanks for your work! what's the exact kernel version?
I didn't get my hands on 4.9 support for the last 2 weeks. is it possible to send me those patches you made for 4.9? That way the automation server will build and post the ko with the latest kernel everyday.

**Comment by barhom** [comment]
Seems LEDE is preparing to move to kernel 4.14 soon. Just a heads up before a lot of work is done on 4.9.

**Comment by Nossiac** [comment]
Yes, I read the maillist from time to time.


My plan is to make these modules stable in kernel 4.4 first. After posting this repo, I got a lot of feedback from github as well as the community. There are still a lot of work pending there. I schedule the tasks by some sort of priority.


For newer kernel, I'm expecting the new official release, like openwrt-18.0X. There would be serveral new modules in the mainstream kernel which is contributted by MediaTek. Hopefully they are going to be available in kernel 4.14. That's awesome.

**Comment by Vonger** [comment]
I will fork into my github and make it support 4.14 later :)

On 9 Feb 2018, at 08:30, barhom <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems LEDE is preparing to move to kernel 4.14 soon. Just a heads up before a lot of work is done on 4.9.

**Comment by Nossiac** [comment]
@Vonger Good! That would be nice if you can share the important fixes you made to the source.

**Comment by Nossiac** [comment]
I'm testing the driver on 4.9.x, latest module will be uploaded sooner this week.

**Comment by BGFWDev** [comment]
It would be great if MediaTek could skip 4.9 and go to the 4.14 release.  It has significant advantages. 

Thanks,

Chris

**Comment by Nossiac** [comment]
already built the driver with latest openwrt trunk (linux-4.9.70), but not verified yet (short of hand).
If anyone want to have a try, you can find the ko here: [http://nossiac.com/download/mtk-wifi-ko/](http://nossiac.com/download/mtk-wifi-ko/)

**Comment by BGFWDev** [comment]
Any plans for MT7615 and MT7612 on MT7623?


-Chris
