### ISSUE TITLE
How to use standard Luci interface to config WiFi settings?

### ISSUE THREAD

**Issue by Dedsic** [Nossiac/mtk-openwrt-feeds#54]
I build a rom with uci2dat and try to config WiFi in luci like you said in README :
>An application that translates "/etc/config/wireless" into MTK's WiFi profiles (e.g. mt7620.dat). You may use it as an adapter to make MTK's WiFi drivers work with standard LuCi's WiFi management. 

This time I try to use the original luci wifi management interface rather than mtk-luci-plugin. But when I flash the rom and boot, There is no wifi config in luci's network menu.
Packages I installed:
* mt7603 mt7612 drivers in MTK properties
* uci2dat

Packages I don't installed:
* rt2x00
* mt76
* cfg80211
* mac80211
* wpad
* supplicant
* mtk-luci-plugin

Did I missed any packages to install? Or there is no way to config wifi in Gui except mtk-luci-plugin?

**Comment by Nossiac** [comment]
First of all, you can find the working example in mtk's openwrt sdk.
to do it on your own, here's some hints:
1. generate "/etc/config/wireless" via uci or script.
2. modify luci's wireless.lua template to add detection of mtk's wifi. (you can search the "vendor" section inside the file, there are several examples)
3. add shell scripts into /lib/wifi (/lib/wifi/mt7620.sh, eg), to impl the down/up/reload/restart api defined by /sbin/wifi.  every time you call /sbin/wifi up/reload, it will call corresponding functions defined in your script.
4. in your own mt76xx_up/reload impl, call "uci2dat" to translate /etc/config/wireless into /etc/wireless/mt76xx/mt76xx.dat
