### ISSUE TITLE
MT7612E with external PA and LNA

### ISSUE THREAD

**Issue by namoaton** [Nossiac/mtk-openwrt-feeds#64]
Hello, I have a very low signal when I use  precompiled driver. And my pc is near and signal  very low
`/home/shello/workspace/lede-1701/build_dir/target-mipsel_24kc_musl-1.1.16/linux-ramips_mt7621/tm7612/src/rlt_wifi_ap/../rlt_wifi/chips/mt76x2.c:2915 assert (ad->TxPower[choffset].Channel == 42)failed
`

**Comment by namoaton** [comment]
I figured out...

**Comment by LINGJP** [comment]
How did you solve this problem?

**Comment by LINGJP** [comment]
> I figured out...

How did you solve this problem?
