### ISSUE TITLE
Use two modules MT7612e simultaneously but second display as MT7602 

### ISSUE THREAD

**Issue by namoaton** [Nossiac/mtk-openwrt-feeds#65]
Hello,
I tried to use two modules mt7612e together but have no succes. One work good, but second dislpay as mt7602....

**Comment by namoaton** [comment]
ok, but where I can find wifi init script ?

**Comment by Nossiac** [comment]
if you were using luci plugin here, then the init scripts was `/sbin/mtkwifi`, which will import scripts like `/lib/wifi/mt76x2.lua` from every drivers you have installed, and call their "mt76x2_up" function.

but seriously, I never saw a product with 2 mt7612 inside,  the best match was 7602+7612.

**Comment by namoaton** [comment]
But it exist... anyway I will try..
