### ISSUE TITLE
Enable on boot. 

### ISSUE THREAD

**Issue by coldchip** [Nossiac/mtk-openwrt-feeds#68]
Hi, How can i enable the kernel module automatically upon boot? 
I am compiling for chip MT7628

**Comment by Pentiumluyu** [comment]
Firstly move mt7628.ko into `'/lib/modules/xx.xx.xx/'`. Then put a file that contains "mt7628" into `'/etc/moodules.d'`.
`touch /etc/modules.d/mt7628`
`echo "mt7628" >> /etc/modules.d/mt7628`

**Comment by coldchip** [comment]
Thanks.
