### ISSUE TITLE
Openwrt kernel has been updated to 4.14.42

### ISSUE THREAD

**Issue by tuanqing** [Nossiac/mtk-openwrt-feeds#70]
Openwrt kernel has been updated to 4.14.42, can also use the old 4.14.34 ko?

**Comment by Nossiac** [comment]
I was busy with something else these days, then I just found that my automation server was shutdown by accident for weeks... now it starts to build again.

**Comment by enmaskarado** [comment]
Hello @Nossiac ,
Almost all the modules have versions for 4.14.44, but the modules for mt76x8 remained in 4.14.34.
I am looking for this module: mt7628-for-mt76x8-linux-4.14.44.ko

**Comment by Nossiac** [comment]
@enmaskarado updated.
