### ISSUE TITLE
WiFi deauth

### ISSUE THREAD

**Issue by coldchip** [Nossiac/mtk-openwrt-feeds#71]
Is there a command that can i kick/deauth WiFi clients out? 

I tried `ubus call hostapd.ra0 del_client '{"addr":"'<mac addr>'", "reason":1, "deauth":true, "ban_time":1000}'` but it doesnt work. 

Anyone have any solutions? Any help would be appreciated.

**Comment by tuanqing** [comment]
You can try using iptables
iptables -I FORWARD  -m mac --mac-source <mac addr> -j DROP

**Comment by Nossiac** [comment]
Try these 2 commands:
```
iwpriv ra0 set DisConnectSta=00:11:22:33:44:55 
iwpriv ra0 set DisConnectAllSta=1 
```

**Comment by coldchip** [comment]
Thanks so much!
