### ISSUE TITLE
 No access to nossiac.com/download/mtk-wifi-ko/  

### ISSUE THREAD

**Issue by marciolm** [Nossiac/mtk-openwrt-feeds#76]
Hello, 
The  http://nossiac.com/download/mtk-wifi-ko/  is apparently off-line and I need the 4.14.x MT2810 and MT28x8 modules. The files in the other repository are too old. Can you update the http://119.23.148.191:8888/mtk-wifi-ko/ repository with the 4.14.x modules ?
Thanks
Márcio

**Comment by enmaskarado** [comment]
Same from here (nossiac.com down).
I need mt7628-for-mt76x8 module for 4.14.50 kernel

**Comment by marciolm** [comment]
The site is back. 
Thank you !
Márcio

**Comment by mahendradeore** [comment]
unable to download from nossiac.com.
